### PR TITLE
Display the list of authors in a readable way.

### PR DESCRIPTION
**Pull request by j-4**
This branch fixes the following points:
 * Displays the authors list in a readable way by formatting the first autor `Last, First` and the others `First Last`
 * Treats the `collaborator` key by the same parsing function with all authors are in the `First Last` style.

Thanks for merging!

### CODE REVIEW

**Comment by j-4** [comment]
I have to add here, that it seems as if the live demo (https://www.cs.cmu.edu/%7Emmv/Veloso.html) does not use a standard bibtex author list? I found, that the name should be specified as "Last, First Middle", in your example it is "First Last". That's why this patch was necessary in the first place.

**Comment by pcooksey** [comment]
This is actually something I have been looking into for awhile (related to #18) . And I will have more time in a month to focus on it since I would like a more general solution. Authors can be listed in many different formats and they go beyond just `First Last` and `Last, First` ([a good description](https://www.tug.org/TUGboat/tb27-2/tb87hufflen.pdf)). There is also a `von` part. Order, commas, and capitalization all matter. So the live demo is correct in using `First Last`, but I agree that there needs to be a better method for displaying the author names.

I also do not see a collaborator key listed for bibtex ([pdf](https://www.andy-roberts.net/res/writing/latex/bibentries.pdf), [wiki](https://en.wikipedia.org/wiki/BibTeX)).

**Comment by j-4** [comment]
Thanks for the clarification with the author field. The specification seems really tricky, I did not know that it is that complicated.
Concerning the collaborator tag: This tag is generated by betterbibtex export from Zotero (https://github.com/retorquere/zotero-better-bibtex) for Presentation Items. There no "coauthors" exist, instead the "Presenter" is the first author, the rest are collaborators. No idea whether this is a standardized thing or custom for betterbibtex.
Thanks for your effort!

**Comment by pcooksey** [comment]
See wiki page [formatting authors](https://github.com/pcooksey/bibtex-js/wiki/Formatting-Authors). 

The collaborators definitely seems to be custom field for betterbibtex. I don't see how the field would be used (in generating a citation) by any program outside of betterbibtex then.

**Comment by pcooksey** [comment]
I've opened up an issue for custom fields like collaborators that need a particular display format.
Issue #32.

**Pull request closed without merging**
