### PR TITLE
✨ Adds support for auto-generated list of keywords

### PR DESCRIPTION
**Pull request by mhaeussermann**
When using a keywords field, the auto-generated list now splits the
keyword list into separate keywords, thus generating a list of unique
keywords to filter by.

### CODE REVIEW

**Comment by mhaeussermann** [comment]
From my tests, the feature seems to work, but as I am not the most advanced JavaScript programmer, it would be great if you could look over it to make sure it does what it is supposed to do. Also, I'd understand it if the feature doesn't fit with the general scope of the project, as "keywords" is not a 'standard' BibTex field.

**Comment by pcooksey** [comment]
Hmm, like you said, I don't really want to bring in non-standard words that aren't bibtex specific. However, I think we can combine your work and else statement right after it. We don't really have to worry about what the bibtex field is (in your case `keywords`) rather its just that you'd like to split the value up by `", "`. I have a working solution. I just need to add some test cases to ensure that it works and continues to work with future changes.

This is what I have for the implementation on the html side. You'd just put whatever you want to split the bibtex field by in `bibtex_split_by`.
```html
<select class="bibtex_search bibtex_generate_keywords" 
        search="keywords" 
        bibtex_split_by=", ">
```
Seem reasonable?

**Comment by pcooksey** [comment]
I pushed the changes to develop. I squashed my changes into your commit to clean up some stuff. I also extended the auto generated select test to ensure the feature is working.

**Comment by mhaeussermann** [comment]
Your changes make the feature way more general and thus more versatile, thank you!

**Comment by pcooksey** [comment]
Thank you for contributing! I'm always happy to see features being used and improved. Closing this pull-request as the commit has been merged into develop 903407343b80d7dfeeb048324df6c31bed697a22.

**Pull request closed without merging**
